DATASET_IDS = ["1903"]

with open('TOKEN_MOS.txt', 'r', encoding='utf-8') as file:
    TOKEN_MOS = file.read()

rule process_target:
    input:
        expand("data/stg/mosdata_dataset{dataset_id}.csv", 
               dataset_id=DATASET_IDS)

rule process_data:
    input: "data/stg/mosdata_dataset{dataset_id}.json"
    output: "data/stg/mosdata_dataset{dataset_id}.csv"
    shell: "process_mosdata --input {input} --output {output}"

rule concat_data:
    input: "data/raw/mosdata_dataset{dataset_id}/CHECKPOINT"
    output: "data/stg/mosdata_dataset{dataset_id}.json"
    params:
        inputdir = "data/raw/mosdata_dataset{dataset_id}"
    shell: "concat_data --input {params.inputdir} --output {output} --is_list"

rule download_data:
    input: "data/raw/mosdata_dataset_trigger"
    output: "data/raw/mosdata_dataset{dataset_id}/CHECKPOINT"
    params: 
        outdir = "data/raw/mosdata_dataset{dataset_id}"
    shell: "load_mosdata --dataset_id {wildcards.dataset_id} --api_key %s --step 200 --output {params.outdir} && touch data/raw/mosdata_dataset{wildcards.dataset_id}/CHECKPOINT" % TOKEN_MOS